[package]
name = "amadeus-core"
version = "0.2.0"
authors = ["Alec Mocatta <alec@mocatta.net>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
derive-new = "0.5"
futures = "0.3"
pin-project = "0.4"
sum = { version = "0.1" }
