[package]
name = "amadeus-aws"
version = "0.2.0"
authors = ["Alec Mocatta <alec@mocatta.net>"]
edition = "2018"

[dependencies]
amadeus-core = { version = "=0.2.0", path = "../amadeus-core" }
futures = { version = "0.3" }
